name: cloudflare
on:
    workflow_dispatch:
    push:
        branches:
            - network_refactor

      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name : Meson Test
          run : DOCKER_BUILDKIT=1 docker build . --file dockerfiles/run_tests --progress plain
    
        - name: Docker Build
          run: DOCKER_BUILDKIT=1 docker build . -f dockerfiles/build_emscripten --output browser-website/src
    
        - name: Deploy
          uses: cloudflare/wrangler-action@v3
          with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            command: pages deploy ./browser-website/src --project-name=warthog

      
